### ISSUE TITLE
服务器端推送时如何判断该调哪个渠道的推送api

### ISSUE THREAD

**Issue by thduan** [Luomingbear/Push#1]
服务器端推送时，是这几个渠道的推送api都调吗？  还是如何判断推送给哪个用户的应该用哪个渠道推送：  小米、华为还是啥

**Comment by Luomingbear** [comment]
客户端调用初始化接口上传设备信息，或者在每一个接口里面放进设备信息作为通用数据上传，需要推送的时候根据该用户的设备信息来进行推送
