### ISSUE TITLE
问一下有应用在app中吗？

### ISSUE THREAD

**Issue by TpOut** [Luomingbear/Push#5]
最近公司也想自己写，但是明白难点在于适配。
想了解下到达率数据之类的

**Comment by Luomingbear** [comment]
对于支持系统级推送的设备如小米，华为，魅族，OPPO和vivo到达率都很高，具体百分比没有看，但是盲测很高，没有出现丢掉的，不过有些时候会有比较长的延时，这个就是服务商的问题了。其他品牌的手机就不行了，我用的锤子手机，基本上杀了应用就收不到了，不过淘宝的通知在我这里也不样退不过来。要提高这些小众手机到达率就需要引入一个第三方推送平台，靠第三方共用消息通道实现消息推送，不过这个和对方手机安装了哪些应用有关。

**Comment by TpOut** [comment]
你这第三方有极光啊？就是也不太稳咯

**Comment by Luomingbear** [comment]
嗯，极光到达率不行

**Comment by TpOut** [comment]
好的。那我自己可能就不把极光放进去了
谢谢。
